version: '3.8'

services:
  frontend:
    build:
      context: ./frontend  # Path to your frontend directory containing Dockerfile
    ports:
      - "3000:80"  # Maps port 80 of the container to port 3000 on the host
    networks:
      - mynetwork
    depends_on:
      - backend

  backend:
    build:
      context: ./backend  # Path to your backend directory containing Dockerfile
    ports:
      - "5000:5000"  # Maps port 5000 of the container to port 5000 on the host
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
