version: '3.8'

services:
  frontend:
    build:
      context: ./frontend  # Path to your frontend directory containing Dockerfile
    ports:
      - "3000:80"  # Maps port 80 of the container to port 3000 on the host

    depends_on:
      - backend

  backend:
    build:
      context: ./backend  # Path to your backend directory containing Dockerfile
    ports:
      - "5000:5000"  # Maps port 5000 of the container to port 5000 on the host
    depends_on:
      - mongodb
    env_file:
      - ./backend/.env  # Load environment variables from .env file

  mongodb:
    image: mongo:latest  # Official MongoDB image from Docker Hub
    container_name: mongodb
    ports:
      - "27017:27017"  # Maps port 27017 of the container to port 27017 on the host
